services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: ${REPO:-ghcr.io/aquamaster-kz/landing:latest}
    # image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/landing:latest
    container_name: aquamaster-landing
    restart: always
    ports:
      - "3000:3000"
    environment:
      CONTACT_EMAIL: ${CONTACT_EMAIL}
      CONTACT_PASS: ${CONTACT_PASS}

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ssl-certificates:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    restart: always
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ssl-certificates:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    entrypoint: ["sh", "-c", "while true; do certbot renew --quiet && sleep 12h; done"]
    restart: always

volumes:
  ssl-certificates:
    driver: local
  certbot-webroot:
    driver: local