FROM nginx:alpine

RUN apk add --no-cache python3 py3-pip

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

RUN chmod 644 /etc/nginx/conf.d/default.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]
