services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ssl-certificates:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    depends_on:
      - certbot
    restart: always
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ssl-certificates:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
      - ./scripts/certbot_entrypoint.py:/usr/local/bin/certbot_entrypoint.py
    entrypoint: ["python", "/usr/local/bin/certbot_entrypoint.py", "aquamaster.kz", "staging"]
    restart: no

  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: ${REPO:-ghcr.io/aquamaster-kz/landing:latest}
    # image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/landing:latest
    container_name: aquamaster-landing
    restart: always
    ports:
      - "3000:3000"

volumes:
  ssl-certificates:
    driver: local
  certbot-webroot:
    driver: local